version: "3.8"
services:

  inti_back:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: inti_back

    # ports:
    #   - "8050:8050"
    #   - "8051:8051"
    expose:
      - 8050

    environment:
      - ASPNETCORE_ENVIRONMENT="Development"
    env_file:
      - .env

  inti_nginx:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - inti_back

    links:
      - inti_back

    ports:
      - "8050:8050"
      - "8080:8080"
