version: "3.8"
services:

  inti_back:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: inti_back
    expose:
      - 8050
      - 8051

    environment:
      - ASPNETCORE_ENVIRONMENT="Development"
    env_file:
      - .env

  inti_nginx:
    image: nginx:stable
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - inti_back

    links:
      - inti_back

    ports:

      - "443:443"
      - "8443:8443"
      - "8050:8050"
      - "8051:8051"
